Dockerfile: replace GTK 2 to 3 to fix XSCT bug on "app create"
On creating the app in XSCT the following error message
would appear:

19:39:24 INFO  : Registering command handlers for Vitis TCF services
19:39:25 ERROR : Error from executing command 'createAppFromDsa': ERROR: The hw specification file given "gateware/syn/hsd_zcu208/system.xsa" does not exists.
19:40:04 INFO  : Registering command handlers for Vitis TCF services
19:40:06 INFO  : Platform repository initialization has completed.
19:40:09 INFO  : Successfully done query RDI_DATADIR
19:40:09 INFO  : plnx-install-location is set to ''
19:40:11 ERROR : Failed to create platform for application project
Reason: Failed to create platform.
19:40:11 ERROR : xsct server communication channel has closed unexpectedly.
java.io.IOException: Communication channel is closed by remote peer
	at org.eclipse.tcf.core.AbstractChannel$1$2.run(AbstractChannel.java:383)
	at org.eclipse.tcf.EventQueue.run(EventQueue.java:98)
	at java.base/java.lang.Thread.run(Thread.java:834)
19:40:11 INFO  : Platform creation cancelled by the user.
19:42:35 INFO  : Registering command handlers for Vitis TCF services
19:42:35 ERROR : xsct server communication channel has closed unexpectedly.
java.lang.NoClassDefFoundError: org/eclipse/ui/wizards/datatransfer/IImportStructureProvider
	at com.xilinx.sdx.cmdline.application.SdxCmdHandlerFactory.<clinit>(SdxCmdHandlerFactory.java:17)
	at com.xilinx.sdx.cmdline.service.SdxTcfCmdServer.command(SdxTcfCmdServer.java:90)
	at com.xilinx.sdx.cmdline.service.SdxTcfCmdServer$1.run(SdxTcfCmdServer.java:76)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: An error occurred while automatically activating bundle org.eclipse.ui.ide (460).
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:126)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:571)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:346)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:398)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:473)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 4 more
Caused by: org.osgi.framework.BundleException: Exception in org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.start() of bundle org.eclipse.ui.ide.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:863)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:791)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1015)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
	at org.eclipse.osgi.container.Module.doStart(Module.java:603)
	at org.eclipse.osgi.container.Module.start(Module.java:467)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:493)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	... 11 more
Caused by: java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons:
	no swt-pi4-gtk-4932r18 in java.library.path: [/media/Xilinx/Vivado/2020.2.2/Vitis/2020.2/tps/lnx64/javafx-sdk-11.0.2/lib, /media/Xilinx/Vivado/2020.2.2/Vitis/2020.2/lib/lnx64.o/Default, /media/Xilinx/Vivado/2020.2.2/Vitis/2020.2/lib/lnx64.o, /media/Xilinx/Vivado/2020.2.2/Vitis/2020.2/tps/lnx64/jre11.0.2/lib/, /media/Xilinx/Vivado/2020.2.2/Vitis/2020.2/tps/lnx64/jre11.0.2/lib//server, /media/Xilinx/Vivado/2020.2.2/Vitis/2020.2/lib/lnx64.o, /media/Xilinx/Vivado/2020.2.2/Vitis/2020.2/lib/lnx64.o/Default, /media/Xilinx/Vivado/2020.2.2/Vitis/2020.2/lib/lnx64.o, /media/Xilinx/Vivado/2020.2.2/Vitis/2020.2/tps/lnx64/python-3.8.3/lib, /media/Xilinx/Vivado/2020.2.2/Vitis/2020.2/lib/lnx64.o/Default, /media/Xilinx/Vivado/2020.2.2/Vitis/2020.2/lib/lnx64.o, /media/Xilinx/Vivado/2020.2.2/Vitis/2020.2/bin/../lnx64/tools/dot/lib, /media/Xilinx/Vivado/2020.2.2/Vitis/2020.2/bin/../lnx64/tools/dot/lib, /usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
	no swt-pi4-gtk in java.library.path: [/media/Xilinx/Vivado/2020.2.2/Vitis/2020.2/tps/lnx64/javafx-sdk-11.0.2/lib, /media/Xilinx/Vivado/2020.2.2/Vitis/2020.2/lib/lnx64.o/Default, /media/Xilinx/Vivado/2020.2.2/Vitis/2020.2/lib/lnx64.o, /media/Xilinx/Vivado/2020.2.2/Vitis/2020.2/tps/lnx64/jre11.0.2/lib/, /media/Xilinx/Vivado/2020.2.2/Vitis/2020.2/tps/lnx64/jre11.0.2/lib//server, /media/Xilinx/Vivado/2020.2.2/Vitis/2020.2/lib/lnx64.o, /media/Xilinx/Vivado/2020.2.2/Vitis/2020.2/lib/lnx64.o/Default, /media/Xilinx/Vivado/2020.2.2/Vitis/2020.2/lib/lnx64.o, /media/Xilinx/Vivado/2020.2.2/Vitis/2020.2/tps/lnx64/python-3.8.3/lib, /media/Xilinx/Vivado/2020.2.2/Vitis/2020.2/lib/lnx64.o/Default, /media/Xilinx/Vivado/2020.2.2/Vitis/2020.2/lib/lnx64.o, /media/Xilinx/Vivado/2020.2.2/Vitis/2020.2/bin/../lnx64/tools/dot/lib, /media/Xilinx/Vivado/2020.2.2/Vitis/2020.2/bin/../lnx64/tools/dot/lib, /usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
	Can't load library: /root/.swt/lib/linux/x86_64/libswt-pi4-gtk-4932r18.so
	Can't load library: /root/.swt/lib/linux/x86_64/libswt-pi4-gtk.so

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:342)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:256)
	at org.eclipse.swt.internal.gtk.OS.<clinit>(OS.java:90)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:209)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:155)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:164)
	at org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.createProblemsViews(IDEWorkbenchPlugin.java:391)
	at org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.start(IDEWorkbenchPlugin.java:348)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:842)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:834)
	... 18 more
19:45:05 INFO  : Registering command handlers for Vitis TCF services
19:45:07 INFO  : Platform repository initialization has completed.
19:45:10 INFO  : Successfully done query RDI_DATADIR
19:45:10 INFO  : plnx-install-location is set to ''
19:45:16 ERROR : Failed to create platform for application project
Reason: Failed to create platform.
19:45:16 ERROR : xsct server communication channel has closed unexpectedly.
java.io.IOException: Communication channel is closed by remote peer
	at org.eclipse.tcf.core.AbstractChannel$1$2.run(AbstractChannel.java:383)
	at org.eclipse.tcf.EventQueue.run(EventQueue.java:98)
	at java.base/java.lang.Thread.run(Thread.java:834)
19:45:16 INFO  : Platform creation cancelled by the user.

The SWT errors pointed me to using GTK3 instead of 2.